#!/usr/bin/python

#Title: Assignment1---Question20
#Author:Merin
#Version:1
#DateTime:03/12/2018 11:40am
#Summary:Write a program to generate a Fibonacci series of numbers.
#        Starting numbers are 0 and 1,  new number in the series is generated by adding previous two numbers in the series.
#        Example : 0, 1, 1, 2, 3, 5, 8,13,21,.....
#        a) Number of elements printed in the series should be N numbers, Where N is any +ve integer.
#        b) Generate the series until the element in the series is less than Max number.


#a) Number of elements printed in the series should be N numbers, Where N is any +ve integer.
#User Input
n=input("Enter the number of elements required in the Fibonacco series:")
#Printing
print "Fibonacci Series:"
if n==1:
    print "0"
elif n==2:
    print "0,1"
else:
    print "0,1",
    a=0;b=1
    for x in range(3,n+1):
        c=a+b
        print ",",c,
        a=b;b=c

#b) Generate the series until the element in the series is less than Max number.

n=input("\nEnter the max number in the Fibonacco series:")

print "Fibonacci Series:"
if n==1:
    print "0,1,1"
else:
    print "0,1,1",
    a=1;b=1;c=a+b
    while c<=n:
        print ",",c,
        a=b;b=c
        c=a+b
